cloud:
  aws:
    credentials:
      access-key: AKIA4HFV4LGCTMLX5TEQ
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false
    

application:
  bucket:
    name: user-profile-service-bucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200MB
      max-file-size: 500MB
      max-request-size: 100MB

server:
  port: 5000
