cloud:
  aws:
    credentials:
      access-key: AKIA22J7BOGYO6RQEREA
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false
    

application:
  bucket:
    name: certificates-storage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 5000
